export const IS_ADMIN = "IS_ADMIN";

export const IS_EMPLOYEE = "IS_EMPLOYEE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const LOGGED_EMPLOYEE = "LOGGED_EMPLOYEE";

export const GET_MATERIAL = "GET_MATERIAL";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";

export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_SELECTIONS = "GET_SELECTIONS";
