export const GET_WEBSITE_CREDENTIALS = "GET_WEBSITE_CREDENTIALS";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_STONES = "GET_STONES";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";

// Customer related
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_FABRICATOR = "GET_FABRICATOR";
export const GET_KITCHEN_AND_BATH = "GET_KITCHEN_AND_BATH";
export const GET_DESIGNER_OR_ARCHITECT = "GET_DESIGNER_OR_ARCHITECT";
export const GET_SELECTIONS = "GET_SELECTIONS";
